name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
            ext: ""
            outfile: server
            buildFlag: ""
          - os: windows-latest
            target: windows-x64
            ext: ".exe"
            outfile: server.exe
            buildFlag: ""
          - os: macos-latest
            target: mac-x64
            ext: ""
            outfile: server
            buildFlag: "--build"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Compile with Nexe
        run: |
          npx nexe index.js \
            -t ${{ matrix.target }} \
            -o build/${{ matrix.outfile }} \
            ${{ matrix.buildFlag }}

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binary
          path: build/${{ matrix.outfile }}
